	Je soussign‚, Fulbert BOUSSATON, ‚tudiant, 
travaillant en freelance pour la soci‚t‚ STYWOX sur le
logiciel d‚nomm‚ 'THE ULTIMATE FIGHT', m'engage … remettre
le travail de programmation dans sa version d‚finitive et
fiable, le 20 Ao—t 1992 … la soci‚t‚ STYWOX. Le travail
‚tant … effectuer sur ATARI ST/TT uniquement.
La r‚mun‚ration contre la version finale du logiciel
pr‚cit‚ sera de 4% sur le prix hors taxe que le
distributeur conc‚dera a la soci‚te STYWOX, par exemplaire,
apr‚s la commercialisation de 'THE ULTIMATE FIGHT'.