					   From:Expose.
					("The Elite Squad")
					   8th June 1988

		Hi Sol,

		If you are reading this then you must be in
		GenSt 2.00, - How did you like the bootup
		screen? (Reply to Expose (me!) on your next
		hack screen).

		Only some files are needed from this disk to
		actually use GenSt 2.00, these are:-

			A) GENST2.PRG
			B) GENST2.INF
			C) MONST2.PRG (if needed)

		The other files on this disk are used for
		linking, libraries, etc...

		I've also put GenSt 1.xx on this disk, its
		files are:-

			A) AMONGEM.PRG
			B) AMONTOS.PRG
			C) GENST.PRG
			D) INSTALL.PRG
			E) MONST.PRG
			F) GENST.RSC
			G) DEMOF.S
			H) GEMINFO.S
			I) MONST.TOS

		If you are intrested in NEW amiga demo's,
		(like the ones on the Amiga Disk enclosed),
		tell T..., and I'll send them off.

		On your next hack, please mention...

		"The Elite Squad" - Thanx
					Expose.

