,$1B,'D',$1B,'D'
      DC.B   $1B,'D',$1B,'D',$1B,'D',$1B,'D'
      DC.B   $1B,'D',$1B,'D',$1B,'D',$1B,'D'
      DC.B   $1B,'D',$1B,'D',$1B,'D',$1B,'D'
      DC.B   $1B,'D',$1B,'C',$1B,'C',$1B,'C'
      DC.B   $1B,'C',$1B,'C',$1B,'C',$1B,'C'
      DC.B   $1B,'C',$1B,'C',$1B,'C',$1B,'C'
      DC.B   $1B,'C',$1B,'C',$1B,'C',$1B,'C'
      DC.B   $1B,'C',$1B,'C',$1B,'C',$1B,'C'
      DC.B   $1B,'C',$1B,'C',$1B,'C',$1B,'C'
      DC.B   $1B,'CTime: '
      DC.B   '        ' 
      DC.B   '  ',$08,$08,$08,$08,$08,$08 
      DC.B   $08,$08,$08,$08,$00,$00
L00C6:DC.B   '  Rate: ' 
      DC.B   $00
L00C7:DC.B   '% [saving'
      DC.B   ']',$00
L00C8:DC.B   '      <A' 
      DC.B   'LT> was ' 
      DC.B   'pressed.' 
      DC.B   ' File is' 
      DC.B   ' skipped' 
      DC.B   '.',$00
L00C9:DC.B   '      La' 
      DC.B   'rger tha' 
      DC.B   'n orig