	dc.b	"Musical Greetings to...",0,0
	dc.b	"Elric: Joe Satriani, Steve",0
	dc.b	"Vai, Allan Holdsworth,",0
	dc.b	"Calvin Russel, Metallica,",0
	dc.b	"Led Zeppelin, AC DC,",0
	dc.b	"Sonic Youth, Leonard Cohen,",0
	dc.b	"Aerosmith and Gary Moore.",-1

	dc.b	"Zappy: -BJORK-",0
	dc.b	"Dweezil Zappa, Morphine",0
	dc.b	"   --Juliana Hatfield--",0
	dc.b	"Joe Satriani, -HEART-",0
	dc.b	"Steve Vai and Bad 4 Good",0
	dc.b	"Whitesnake, Gary Moore,",0
	dc.b	"Yngwie Malmsteen, ZZTop,",0
	dc.b	"Van Halen, Saint Etienne,"
	dc.b	-1
	
	dc.b	"Extreme, Sugarcubes, Ride,",0
	dc.b	"Suede, #Liz Phair#, Pulp,",0
	dc.b	"Sheryl Crow, Jan Cyrka,",0
	dc.b	"Pat Benatar, Vinnie Moore,",0
	dc.b	"Rickie Lee Jones, Breeders,",0
	dc.b	"Deep Purple, Lemonheads,",0
	dc.b	"Stevie Ray Vaughan, Del",0
	dc.b	"Amitri and Kristin Hersh."
	dc.b	-1
